### PR TITLE
doc(README): Add CI & npm badges

### PR DESCRIPTION
**Pull request by jhermsmeier**
Change-Type: patch

### CODE REVIEW

**Review by jviotti — APPROVED** [review]

**Comment by jviotti** [comment]
@jhermsmeier Lets publish a new version from this module to npm so we can close the privacy related item.

**Comment by jviotti** [comment]
@hedss Should we enable VersionBot on this repo?

**Comment by jhermsmeier** [comment]
@jviotti Release PR: https://github.com/resin-io-modules/resin-corvus/pull/29 – I'm wondering if we should fix the builds before cutting a new release? It's just a matter of either making a few changes to support Node 4, or drop Node 4 support...

**Comment by jviotti** [comment]
Sounds good to me!

**Comment by jhermsmeier** [comment]
@jviotti mended Node 4 support in #30 – will rebase the release once that's in; then tag & bag it

**Pull request merged**
